### ISSUE TITLE
Updated ViMacs/vendor packages?

### ISSUE THREAD

**Issue by agsdot** [ahmadseleem/ViMacs#1]
Was wondering when/if you are going to update the packages in the vendor directory (e.g. neotree has seen quite a few updates in the past two months).

Also was curious as to if the project could use git submodules to source these packages as well?

**Comment by ahmadseleem** [comment]
@agsdot 
Hi, I'm sorry it took me a while to respond back.
I was very busy.

but, I'll try to look how to do use git submodules done, God Willing. The problem though that I customize many somethings to get these packages to work the Vim way.
It need to be reorganized. any pull requests or forks are welcome, too.

hopefully next week I should know.
Thank you!
